api_hash: your_api_hash
api_id: your_api_id
chat_id: telegram_chat_id
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
- animation
datasource:
  database: tg_message
  host: localhost
  password: root
  user: root
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
max_file_size_mb: 4
notice_url: http://xxxx/xxxx/
proxy:
  hostname: 192.168.100.10
  port: 7890
  scheme: http
push_keywords:
- 红包
push_users:
- username1
